### ISSUE TITLE
Improvements on documentation

### ISSUE THREAD

**Issue by marioidival** [hermeznetwork/price-updater-service#37]
[ ] - Create a documentation to setup the price updater
[ ] - Improvements to README
 - What's commands are required
 - Add `$` in a text command to users know that command is runnable by binary

**Comment by invocamanman** [comment]
I would add in the README the following things:
1. Warn the user that the price-updater will update the DDBB
2. I would add a "quick-guide" a simple batch of commands, that any user can just paste and have the price-updater running

Also i would change:
1. It could be worth it have another provider wich would be "hardcoded", and then the hardcoded prices would be all in the same file
2. The folder `assests` should be renamed as `assets` i think
