### ISSUE TITLE
Price updater using hermez-node database

### ISSUE THREAD

**Issue by krlosMata** [hermeznetwork/price-updater-service#42]
We had a chat with @laisolizq and we have some questions regarding price-updater functionality xD

Price-updater service requires some environment variables which includes connection to postgres hermez database:
- does it means that price-updater write directly to the hermez-node database ?
- continuing the question before, does API responses reads from hermez postgres database or price-updater has its own database ?
- wonder if price-updater can run on an external machine a part from hermez-node and if the price-updater could run without setting those variables and be an external service for anyone that needs to fetch prices

thanks !!

**Comment by jeffprestes** [comment]
This was clarified in an internal meeting.
